lhabilleur/la_habilleur/urls.py
from django.conf.urls.defaults import patterns, url
from la_habilleur import views

urlpatterns = patterns(
    '',
    url(r'^$', views.display_wardrobe, name='display-wardrobe'),
    url(r'^enter-suit/', views.enter_suit, name = 'enter-suit'),
    url(r'^view-suit-rank/', views.view_suit_rank, name = 'view-suit-rank'),
    url(r'^add-to-wardrobe/', views.add_to_wardrobe, name='add-to-wardrobe'),
    url(r'^drop-wardrobe/', views.drop_wardrobe, name='drop-wardrobe'),
    url(r'^drop-suits/', views.drop_suits, name='drop-suits'),
    url(r'^manage-suits/(?P<suit_id>\d*)/?', views.manage_suits,
        name='manage-suits'),
    url(r'^add-suit/', views.add_suit, name='add-suit'),
    # Convention: json-giving urls include _
    url(r'^get_wardrobe/', views.get_wardrobe, name='get_wardrobe')
)

lhabilleur/urls.py
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.contrib import admin
from django.conf import settings
from django.http import HttpResponseRedirect
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
#    (r'^static/(?P<path>.*)$', 'django.views.static.serve',
#     {'document_root': settings.STATIC_ROOT}),
    url(r'^la_habilleur/', include('la_habilleur.urls',
                                   namespace='la_habilleur')),
     url(r'^$', lambda x: HttpResponseRedirect("la_habilleur/"))
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
)

lhabilleur/la_habilleur/models.py
from django.db import models
from picklefield.fields import PickledObjectField


class Wardrobe(models.Model):
    username = models.CharField(max_length = 100)
    wardrobe = PickledObjectField()
    suits = PickledObjectField()

    def __unicode__(self):
        return self.username

    def best_suits(self):
        return None

    def add_cloth(self):
        return None

    def fill_the_suit(self):
        return None

lhabilleur/la_habilleur/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseBadRequest
from django.shortcuts import get_object_or_404, render
from django.utils.datastructures import MultiValueDictKeyError
from django.utils import simplejson

import init_and_cache
import core
from la_habilleur.models import Wardrobe
from core.color_rank import hsv_to_hex

def index(request):
    return HttpResponse("Hello")

def display_wardrobe(request):
    the_wardrobe = get_object_or_404(Wardrobe, pk=1)
    return render(request, 'la_habilleur/add_cloth.html', {
        'the_wardrobe': the_wardrobe.wardrobe,
        'cloth_db':  init_and_cache.cloth_db()})

def add_to_wardrobe(request):
    the_wardrobe = get_object_or_404(Wardrobe, pk=1)
    try:
        id_to_add = init_and_cache.cloth_db().get_by_name(
            request.POST['cloth_name']).id
    except (ValueError, MultiValueDictKeyError, KeyError):
        return render(request, 'la_habilleur/add_cloth.html', {
         'the_wardrobe': the_wardrobe.wardrobe,
            'cloth_db': init_and_cache.cloth_db(),
            "error_message": "Invalid item"})
    try:
        color_to_add = tuple(core.color_rank.hex_to_hsv(
            [request.POST['cloth_color'].strip('#'),])[0])
    except (ValueError, MultiValueDictKeyError, KeyError, TypeError):
        return render(request, 'la_habilleur/add_cloth.html', {
            'the_wardrobe': the_wardrobe.wardrobe,
            'cloth_db': init_and_cache.cloth_db(),
            "error_message": "Invalid color"})

    cloth_to_add = core.cloth_db.Cloth(id_to_add, color_to_add)
    if not isinstance(the_wardrobe.wardrobe, list):
        the_wardrobe.wardrobe = list()
    if cloth_to_add in the_wardrobe.wardrobe:
        return render(request, 'la_habilleur/add_cloth.html', {
            'the_wardrobe': the_wardrobe.wardrobe,
            'cloth_db': init_and_cache.cloth_db(),
            "error_message": "Duplicate entry"})
    the_wardrobe.wardrobe.append(cloth_to_add)
    the_wardrobe.save()
    return HttpResponseRedirect(reverse('la_habilleur:display-wardrobe'))

def drop_wardrobe(request):
    the_wardrobe = get_object_or_404(Wardrobe, pk=1)
    the_wardrobe.wardrobe = []
    the_wardrobe.save()
    return HttpResponseRedirect(reverse('la_habilleur:display-wardrobe'))

def drop_suits(request):
    the_wardrobe = get_object_or_404(Wardrobe, pk=1)
    the_wardrobe.suits = []
    the_wardrobe.save()
    return HttpResponseRedirect(reverse('la_habilleur:manage-suits'))

def enter_suit(request):
    return render(request, 'la_habilleur/calc_suit_rank.html', {})

def view_suit_rank(request):
    cloth_ids = request.POST['suit']
    cloth_ids = cloth_ids.split()
    cloth_ids = map(int, cloth_ids)
    ranker = init_and_cache.ranker()
    rank = ranker.rank_items(cloth_ids)
    return HttpResponse(rank)

def add_suit(request):
    """Simple debug function for adding suits"""
    the_wardrobe = get_object_or_404(Wardrobe, pk=1)
    cloth_ids = request.POST['suit']
    cloth_ids = cloth_ids.split()
    cloth_ids = tuple(map(int, cloth_ids))
    if len(cloth_ids) == 0:
          return HttpResponseBadRequest(
            "Can't enter an empty suit")
    if not init_and_cache.cloth_db().check_suit(cloth_ids):
        return HttpResponseBadRequest(
            "This is not a suit. Some ids belong to the same slot")
    if not isinstance(the_wardrobe.suits, list):
        the_wardrobe.suits = list()
    the_wardrobe.suits.append(core.cloth_db.assemble_grey_suit(cloth_ids))
    the_wardrobe.save()
    return HttpResponse("Added")

def manage_suits(request, suit_id):
    the_wardrobe = get_object_or_404(Wardrobe, pk=1)
    try:
        suit = the_wardrobe.suits[int(suit_id)]
    except ValueError:
        suit = []
    except IndexError:
        return HttpResponseBadRequest("No suit with such id")

    return render(request, 'la_habilleur/manage_suits.html', {
        'the_wardrobe': the_wardrobe.wardrobe,
        'cloth_db':  init_and_cache.cloth_db(),
        'suit': suit,    # Suit being displayed
        'suits': the_wardrobe.suits   # All suits of the user
        })

def get_wardrobe(request):
    """Returns JSON with the user wardrobe. Format:
    1. json of cloth
    2. Each cloth: json of
    a. id - python cloth_db id
    b. name - python cloth_db name
    c. color - hex color
    d. slot - slot id, as in slot iterator
    """
    the_wardrobe = get_object_or_404(Wardrobe, pk=1)
    cloth_db_ = init_and_cache.cloth_db()
    response = list()
    for cloth in the_wardrobe.wardrobe:
        cloth_dict = dict()
        cloth_in_db = cloth_db_.get_by_id(cloth.id)
        cloth_dict['color'] = hsv_to_hex(cloth.color)
        cloth_dict['name'] = cloth_in_db.name
        cloth_dict['slot'] = cloth_db_.slot_ids[cloth_in_db.slot]
        cloth_dict['id'] = cloth.id
        response.append(cloth_dict)

    return HttpResponse(
        simplejson.dumps(response, ensure_ascii=False),
        content_type = 'application/json; charset=utf8'
    )

lhabilleur/la_habilleur/templates/la_habilleur/add_cloth.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7, IE=edge">
  <title>L'habilleur Intelligente</title>
  {% load static %}
  {% get_static_prefix as STATIC_PREFIX %}
  <link href="{{ STATIC_PREFIX }}css/bootstrap-tree.css" rel="stylesheet">
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" media="screen">
  <link href="{{ STATIC_PREFIX }}la_habilleur/css/bootstrap-colorpicker.css"  rel="stylesheet">
  <link href="{{ STATIC_PREFIX }}la_habilleur/css/stylesheet.css"  rel="stylesheet">
  <link href="{{ STATIC_PREFIX }}la_habilleur/lhabilleur_blue.ico" rel="shortcut icon" type="image/x-icon">
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/la_habilleur/">L'habilleur Intelligente</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="manage"><a href="/la_habilleur/">Manage wardrobe</a></li>
        </ul>
        <form class="navbar-form navbar-right">
          <div class="form-group email">
            <input type="text" placeholder="Email" class="form-control">
          </div>
          <div class="form-group passwd">
            <input type="password" placeholder="Password" class="form-control">
          </div>
          <button type="submit" class="btn btn-success">Sign in</button>
        </form>
      </div><!--/.navbar-collapse -->
    </div>
  </div>
  <div class="container body">
    <div class="row error-message">
      {% if error_message %}
          <div class="alert alert-error">
            <p><strong>{{ error_message }}</strong></p>
          </div>
      {% endif %}
    </div>
    <div class="row manage-wardrobe">
      <div class="col-lg-3 current-wardrobe" style="color:#000000">
        <div class="wardrobe-header" style="font-size:150%">Current wardrobe</div>
        <br>
        <ol>
          {% load la_habileur_template %}
          {% for ind in the_wardrobe %}
            <li style="margin-right: 60px">
              {{ cloth_db.clothes_by_id|print_element:ind.id }}
              <div style="float: right">
              <canvas width="20" height="10" style="border:1px solid #000000;
              background-color:{{ ind.color|hsv_to_hex }};">
              </canvas>
              </div>
            </li>
        {% endfor %}
        </ol>
        {% load url from future %}
        <div class="drop" style="margin-top:30px">
          <a href="{% url 'la_habilleur:drop-wardrobe' %}"
         class="btn btn-default btn-large" style="width:150px">Drop wardrobe</a>
        </div>
        <div class="manage mng-wardrobe" style="margin-top:10px">
          <a href="{% url 'la_habilleur:display-wardrobe' %}" class="btn btn-default btn-large" style="width:150px">Manage wardrobe</a>
        </div>
        <div class="manage mng-suits" style="margin-top:10px">
          <a href="{% url 'la_habilleur:manage-suits' ''%}" class="btn btn-default btn-large" style="width:150px">Manage suits</a>
        </div>
        <br>
      </div>
      <div class="col-lg-4 wardrobe-items-tree">
        <div class="well">
          <ul class="tree">
            {% for slot in cloth_db.clothes_by_slot.iterkeys %}
              <li>
                <a href="#" style="color:#000000" class="tree-toggle closed" data-toggle="branch"
                data-value="Bootstrap_Tree">{{ slot }} </a>
                <ul class="branch closed">
                  {% for cloth in cloth_db.clothes_by_slot|lookup:slot %}
                    <li><a href="#" style="color:#000000"
                    onclick="UpdateSelection('{{ cloth.name }}')">{{ cloth.name }}</a></li>
                  {% endfor %}
                </ul>
              </li>
            {% endfor %}
          </ul>
        </div><!--/.well -->
      </div>
      <div class="col-lg-4 add-item-form" style="color:#000000">
        <div class="add-header" style="font-size:150%">Add item</div>
        <br>
        <div class="row">
          <form action="{% url 'la_habilleur:add-to-wardrobe' %}" method="post" class="form-inline">
            <div id="cloth_color_selector" class="col-lg-2 input-append color bscp" data-color="#000000">
              <input type="hidden" name="cloth_color" value="#000000">
              <span class="add-on"><i></i></span>
            </div>
            {% csrf_token %}
            <div class="col-lg-6">
              <input type="text" class="form-control" placeholder="Text input" name="cloth_name" id="cloth_to_add" autocomplete="off"
               data-provide="typeahead"
               data-items="4" data-source='[{% for cloth_list in cloth_db.clothes_by_slot.itervalues %}
               {% for cloth in cloth_list %} "{{ cloth.name }}"
               {% if not forloop.parentloop.last or not forloop.last %},{% endif %}
               {% endfor %}
               {% endfor %}
               ]'>
            </div>
            <div class="col-lg-4 add-button">
              <input class="btn btn-default" type="submit" value="Add">
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.js">
  </script>
  <script src="{{ STATIC_PREFIX }}js/bootstrap-tree.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="{{ STATIC_PREFIX }}la_habilleur/js/bootstrap-colorpicker.js"></script>
  <script src="{{ STATIC_PREFIX }}la_habilleur/js/display_wardrobe.js"></script>
</body>
</html>

lhabilleur/la_habilleur/templates/la_habilleur/calc_suit_rank.html
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
{% load url from future %}
<form action="{% url 'la_habilleur:view-suit-rank' %}" method="post">
{% csrf_token %}
    <input type="text" name="suit" id="suit" />
<input type="submit" value="Calc" />
</form>

<form action="{% url 'la_habilleur:add-suit' %}" method="post">
{% csrf_token %}
    <input type="text" name="suit" id="suit" />
<input type="submit" value="Add" />
</form>

lhabilleur/la_habilleur/templates/la_habilleur/manage_suits.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7, IE=edge">
  <title>L'habilleur Intelligente</title>
  {% load static %}
  {% load url from future %}
  {% load la_habileur_template %}
  {% get_static_prefix as STATIC_PREFIX %}
  <link href="{{ STATIC_PREFIX }}css/bootstrap-tree.css" rel="stylesheet">
  <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" media="screen">
  <link href="{{ STATIC_PREFIX }}la_habilleur/css/bootstrap-colorpicker.css"  rel="stylesheet">
  <link href="{{ STATIC_PREFIX }}la_habilleur/css/stylesheet.css"  rel="stylesheet">
  <link href="{{ STATIC_PREFIX }}la_habilleur/lhabilleur_blue.ico" rel="shortcut icon" type="image/x-icon">
</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/la_habilleur/">L'habilleur Intelligente</a>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li class="manage"><a href="/la_habilleur/">Manage wardrobe</a></li>
        </ul>
        <form class="navbar-form navbar-right">
          <div class="form-group email">
            <input type="text" placeholder="Email" class="form-control">
          </div>
          <div class="form-group passwd">
            <input type="password" placeholder="Password" class="form-control">
          </div>
          <button type="submit" class="btn btn-success">Sign in</button>
        </form>
      </div><!--/.navbar-collapse -->
    </div>
  </div>
  <div class="container body">
    <div class="row error-message">
      {% if error_message %}
          <div class="alert alert-error">
            <p><strong>{{ error_message }}</strong></p>
          </div>
      {% endif %}
    </div>
    <div class="row manage-suits">
      <div class="col-lg-3 current-suits" style="color:#000000">
        <div class="suits-header" style="font-size:150%">Current suits</div>
        <br>
        <ol>
          {% for suit in suits %}
          <li style="margin-right: 120px">
            <a href="{% url 'la_habilleur:manage-suits' forloop.counter0 %}">{{ suit|print_suit }}</a>
          </li>
          {% endfor %}
        </ol>
        <div class="drop-suits" style="margin-top:30px">
          <a href="{% url 'la_habilleur:drop-suits' %}"
         class="btn btn-default btn-large" style="width:150px">Drop suits</a>
        </div>
        <div class="manage mng-wardrobe" style="margin-top:10px">
          <a href="{% url 'la_habilleur:display-wardrobe' %}" class="btn btn-default btn-large" style="width:150px">Manage wardrobe</a>
        </div>
      </div>
      <div class="col-lg-4 current-wardrobe-items-tree">
        <div class="well">
          <ul class="tree">
            {% for slot, slot_id in cloth_db.slot_ids.iteritems %}
            <li>
                <a href="#" class="tree-toggle closed" style="color:#000000" data-toggle="branch"
                 data-value="Bootstrap_Tree" id="tree_slot_{{ slot_id }}"
                 onclick="UpdateSelectionAndColor('{{ cloth.name }}')">
                {{ slot }} - <span id="dressed_slot_{{ slot_id }}">
                  {{ suit|print_find_by_slot:slot }}</span></a>
                          <ul class="branch closed">
                {% for cloth in the_wardrobe|clothes_from_wardrobe_by_slot:slot %}
                <li><a href="#"
                 onclick="AddToCurrentSuit({{ the_wardrobe|index:cloth }})">
              {{ cloth|color_background_cloth }}</a>
                </li>
                {% endfor %}
                          </ul>
            </li>
            {% endfor %}
          </ul>
        </div><!--/.well --></div>
      <div class="col-lg-4 add-item-form" style="color:#000000">
        <div class="add-header" style="font-size:150%">Add item</div>
        <br>
        <div class="row">
          <div id="cloth_color_selector" class="col-lg-2 input-append color bscp" data-color="#000000">
            <input type="hidden" name="cloth_color" value="#000000">
            <span class="add-on"><i></i></span>
          </div>
          <div class="col-lg-6">
            <input type="text" class="form-control" name="cloth_name" id="cloth_to_add" autocomplete="off"
            data-provide="typeahead"
            data-items="4" data-source='[{% for cloth_list in cloth_db.clothes_by_slot.itervalues %}
            {% for cloth in cloth_list %} "{{ cloth.name }}"
            {% if not forloop.parentloop.last or not forloop.last %},{% endif %}
            {% endfor %}
            {% endfor %}
            ]'>
          </div>
          <div class="col-lg-4 add-button">
            <button type="button" class="btn btn-default"
             onclick="AddToCurrentSuit()">Add</button>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.js">
  </script>
  <script src="{{ STATIC_PREFIX }}js/bootstrap-tree.js"></script>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
  <script src="{{ STATIC_PREFIX }}la_habilleur/js/bootstrap-colorpicker.js"></script>
  <script src="{{ STATIC_PREFIX }}la_habilleur/js/manage_suits.js"></script>
  <script  src="{{ STATIC_PREFIX }}js/tinycolor.js" type="text/javascript"></script>
</body>
</html>